# Generated by Django 4.1.3 on 2022-11-12 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cook',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name'], 'verbose_name': 'dish', 'verbose_name_plural': 'dishes'},
        ),
        migrations.AlterModelOptions(
            name='dishtype',
            options={'ordering': ['name'], 'verbose_name': 'dish_type'},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='dishes',
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', to='workspace.ingredient'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='cooks',
            field=models.ManyToManyField(related_name='dishes', to=settings.AUTH_USER_MODEL),
        ),
    ]
